---
- name: Updates apt cache
  action: apt update_cache=true
  sudo: yes

- name: Installing zabbix-agent
  apt: pkg=zabbix-agent
       state=present
       update_cache=yes
       cache_valid_time=3600
  sudo: yes
  notify:
    - zabbix-agent sevice reconfig

#- name: Enable the service
#  service: name=zabbix-agent
#           enabled=yes
#  sudo: yes
