---
- name: Zabbix-agent packages install
  yum: name=zabbix-agent
       enablerepo=zabbix
       state=present
  notify:
    - zabbix-agent sevice reconfig

- include: 01-zabbix-agent-config.yml

- name: Firewall configure | back-end port open
  firewalld: zone=public
             port={{ item }}
             permanent=true
             state=enabled
  with_items: ZabbixAgentPort
  notify:
    - firewall reload
