---
- name: Xterm install
  yum: name='xfce4-terminal'
       enablerepo=epel
       state=present

- name: Adobe Flash install
  yum: name='flash-plugin'
       enablerepo=adobe-linux-x86_64
       state=present

- name: Gnome PackageKit
  yum: name='gnome-packagekit'
       state=present

### FireFox
- name: FireFox
  yum: name='firefox'
       state=present

- name: FireFox Java enable
  command: alternatives --install /usr/lib/mozilla/plugins/libjavaplugin.so libjavaplugin.so /usr/java/jdk1.8.0_45/jre/lib/amd64/libnpjp2.so 20000

### Foxit PDF
- name: Foxit install | source download
  yum: name='http://cdn02.foxitsoftware.com/pub/foxit/reader/desktop/linux/1.x/1.0/enu/FoxitReader-1.0-1.i386.rpm'

#- name: Libreoffice |download
#  unarchive: src=http://download.documentfoundation.org/libreoffice/stable/5.0.2/rpm/x86_64/LibreOffice_5.0.2_Linux_x86-64_rpm.tar.gz dest=/home/Administrator/Загрузки/libreoffice/LibreOffice_5.0.2_Linux_x86-64_rpm.tar.gz

#- name: Libreoffice-unpackages
#   unarchive: src=/home/Administrator/Загрузки/libreoffice/LibreOffice_5.0.2_Linux_x86-64_rpm.tar.gz
#   dest=/home/Administrator/Загрузки/libreoffice/LibreOffice_5.0.2_Linux_x86-64.rpm

- name: Libreoffice install
  yum: name='libreoffice' state=latest

- name: Libreoffice install langpack
  yum: name='libreoffice-langpack-ru' state=latest

- name: Gedit install
  yum: name='gedit' state=latest
