---
- name: EPEL repository
  yum: name='http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm'
       state=present
  notify:
    - epel repo disable

- name: Nux Dextop repository
  yum: name='http://li.nux.ro/download/nux/dextop/el7/x86_64/nux-dextop-release-0-5.el7.nux.noarch.rpm'
       state=present
  notify:
    - nux repo disable

- name: Adobe repository
  yum: name='http://linuxdownload.adobe.com/adobe-release/adobe-release-x86_64-1.0-1.noarch.rpm'
       state=present
  notify:
    - adobe repo disable

- name: Zabbix repository
  yum: name='http://repo.zabbix.com/zabbix/2.4/rhel/7/x86_64/zabbix-release-2.4-1.el7.noarch.rpm'
       state=present
  notify:
    - zabbix repo disable

- name: Nginx repository
  yum: name='http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm'
       state=present
  notify:
    - nginx repo disable
