---
- name: Base packages install
  yum: name={{ item }}
       state=present
  with_items: BasePackages

- name: JRE get
  command: 'wget -q -O "/usr/local/src/jre-8u45-linux-x64.rpm" --no-cookies --no-check-certificate --header "Cookie: oraclelicense=accept-securebackup-cookie" "http://download.oracle.com/otn-pub/java/jdk/8u45-b14/jre-8u45-linux-x64.rpm"  creates="/usr/local/src/jre-8u45-linux-x64.rpm"'

- name: JRE install
  yum: name='/usr/local/src/jre-8u45-linux-x64.rpm'
